//! A profile **generated by a motion in the plane**: the envelope of a tool carried by a planar
//! motion, as a curve of the drawing (issue #61, proposal 2; spec §6.15.1).
//!
//! `cut := envelope(tool, under: m, from: a, to: b)` with `tool` a point, line, circle, arc or
//! curve of the sheet and `m` a planar motion (`motion(about: point, …)`, `motion(along: line,
//! …)`, `motion(of: …, relative_to: …)`) is the curve `C(t)`, `t` the roll in degrees: the point
//! of the tool at roll `t` where the tool is cutting.  The tool is drawn where it stands at roll
//! 0; the motion carries it to `X(s, t) = M(t)·T(s)`, `s` the tool's own parameter, and the
//! cutting point is where the tool's tangent runs along the velocity of the material point under
//! it, `F(s, t) = X_s × X_t = 0` — the envelope condition `n · v = 0`, which in the plane says
//! the normal passes through the instant centre.  One scalar unknown, `s`, per roll.
//!
//! The motion's numbers and the tool's are the curve's **columns** — the centres it turns about,
//! the line it slides along, the tool's own coordinates — so a contact against a generated
//! profile moves the tool and the motion to suit, which is what synthesising a conjugate means.
//!
//! **Exact orders.**  `C`, `C'` and `C''` are read along `t + ε` in Taylor arithmetic
//! (`taylor::Jet`): the root `s(ε)` order by order, each one division by `F_s` (the scalar
//! implicit function theorem, Wagner–Walther–Schaefer once more), then `X(s(ε), t + ε)`.  A
//! point, line, circle or arc is exact at every order, so its profile is exact to `C'''` — and
//! may cut in its turn, read as its Taylor series (`Tool::Envelope`).  A curve tool's tape stops
//! at its third derivative, so its profile's `C'''` and every gradient along the columns are
//! differences — read only by Jacobians, never by a residual.
//!
//! **Which root.**  A line tool cuts once; a circle twice, on the line from its centre through
//! the instant centre: `side` says which, the point nearer the instant centre (`near`, a roller's
//! working side) or the farther.  A curve tool may cut in several places: the roots at the
//! anchor roll are found by a scan of the tool's interval, `side` picks among them, and the
//! choice is carried by continuity to every other roll, as a trace carries its branch.

use crate::fmath::Det;
use crate::locus::{contact_prefix, key_of, outer_of, Frame, Val};
use crate::taylor::Jet;
use crate::tape;

/// What cuts.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Tool {
    Point,
    Line,
    Circle,
    /// An arc cuts as its circle does; its radius is its seventh column.
    Arc,
    /// A curve from a computed point: its tapes, its constants and its interval.
    Curve,
    /// A profile generated by a point, line, circle or arc, cutting in its turn — a rack-cut
    /// tooth cutting its mate.  Its columns are its own (its tool's and its motion's).
    Envelope,
}

impl Tool {
    const ALL: [Tool; 6] = [Tool::Point, Tool::Line, Tool::Circle, Tool::Arc, Tool::Curve, Tool::Envelope];

    fn code(self) -> f64 {
        Tool::ALL.iter().position(|&t| t == self).unwrap() as f64
    }

    fn of(code: f64) -> Option<Tool> {
        Tool::ALL.iter().copied().find(|t| t.code() == code)
    }

    /// Exact at every order, so the root and the cut are too, to the third (`orders`).
    pub fn analytic(self) -> bool {
        !matches!(self, Tool::Curve | Tool::Envelope)
    }
}

/// One step of the motion's postfix program, each number where it stands in the outer vector
/// `[t, θ…, values…]`: a turn about a centre at a ratio and phase (radians), a slide along a
/// line by an advance per turn, and the relative of the two before it (`of` the first,
/// `relative_to` the second).
#[derive(Clone, Copy, Debug, PartialEq)]
pub enum Op {
    Turn { centre: usize, ratio: usize, phase: usize },
    Slide { line: usize, advance: usize },
    Relative,
}

/// What a curve or generated tool carries besides its columns.
pub enum ToolBody<'a> {
    None,
    /// Its two tapes, its constants and its interval; its columns are the first `n_theta`.
    Curve { n_theta: usize, x: &'a [f64], y: &'a [f64], values: &'a [f64], domain: (f64, f64) },
    /// Its own encoding, the numbers its motion was given, its anchor and its interval.
    Envelope { n_theta: usize, flat: &'a [f64], values: &'a [f64], anchor: f64, domain: (f64, f64) },
}

const DEG: f64 = std::f64::consts::PI / 180.0;
/// The widest outer vector `[t, θ…, values…]`: the columns are held to `tape::MAX_VARS` (a
/// contact's gradient is that wide), the motion's numbers, constants, ride past them.
pub const OUTER_MAX: usize = 2 * tape::MAX_VARS;
const NEWTON_MAX: usize = 40;
/// The deepest motion program: a stack this deep is all `motion` keeps.
const STACK: usize = 16;
/// Samples of a curve tool's interval when its roots are looked for at the anchor.
const SCAN: usize = 128;
/// Continuation steps from the anchor roll to the one asked for, for a curve tool.
const MARCH: usize = 32;

/// A compiled generated profile, held as its encoding — what rides in a contact's constants:
/// `[n_theta, tool, side, n_ops, ops…, tool body…]`, written by `new` and read by `view` and
/// nowhere else.  A turn is `[1, centre, ratio, phase]`, a slide `[2, line, advance]`, a
/// relative `[3]`.  A curve tool's body is `[n_theta, lx, ly, x…, y…, n_values, values…, from,
/// to]`, a generated tool's `[n_theta, n_values, values…, anchor, from, to, len, flat…]`.
#[derive(Clone, Debug)]
pub struct Generated {
    pub flat: Vec<f64>,
}

impl Generated {
    pub fn new(n_theta: usize, tool: Tool, side: f64, ops: &[Op], body: ToolBody) -> Generated {
        let mut f = vec![n_theta as f64, tool.code(), side, ops.len() as f64];
        for op in ops {
            match *op {
                Op::Turn { centre, ratio, phase } => f.extend([1.0, centre as f64, ratio as f64, phase as f64]),
                Op::Slide { line, advance } => f.extend([2.0, line as f64, advance as f64]),
                Op::Relative => f.push(3.0),
            }
        }
        match body {
            ToolBody::None => {}
            ToolBody::Curve { n_theta, x, y, values, domain } => {
                f.extend([n_theta as f64, x.len() as f64, y.len() as f64]);
                f.extend_from_slice(x);
                f.extend_from_slice(y);
                f.push(values.len() as f64);
                f.extend_from_slice(values);
                f.extend([domain.0, domain.1]);
            }
            ToolBody::Envelope { n_theta, flat, values, anchor, domain } => {
                f.extend([n_theta as f64, values.len() as f64]);
                f.extend_from_slice(values);
                f.extend([anchor, domain.0, domain.1, flat.len() as f64]);
                f.extend_from_slice(flat);
            }
        }
        Generated { flat: f }
    }

    /// What cuts.
    pub fn tool(&self) -> Option<Tool> {
        self.flat.get(1).copied().and_then(Tool::of)
    }
}

/// The flat form, read.
struct View<'a> {
    n_theta: usize,
    tool: Tool,
    side: f64,
    ops: Vec<Op>,
    curve: Option<CurveTool<'a>>,
    inner: Option<Box<InnerTool<'a>>>,
}

struct CurveTool<'a> {
    n_theta: usize,
    x: &'a [f64],
    y: &'a [f64],
    values: &'a [f64],
    domain: (f64, f64),
}

/// A generated tool: its own view, the numbers its motion was given, the roll it is anchored at
/// and its interval.  Its columns are the first `view.n_theta` of the outer view's.
struct InnerTool<'a> {
    view: View<'a>,
    values: &'a [f64],
    anchor: f64,
    domain: (f64, f64),
}

impl View<'_> {
    /// The interval a curve or generated tool runs over — where its cuts are looked for.
    fn tool_domain(&self) -> Option<(f64, f64)> {
        match (&self.curve, &self.inner) {
            (Some(c), _) => Some(c.domain),
            (_, Some(e)) => Some(e.domain),
            _ => None,
        }
    }
}

fn view(flat: &[f64]) -> Option<View<'_>> {
    let g = |i: usize| flat.get(i).copied().filter(|v| v.is_finite());
    let ix = |i: usize| g(i).filter(|&v| v >= 0.0).map(|v| v as usize);
    let n_theta = ix(0)?;
    let tool = Tool::of(g(1)?)?;
    let side = g(2)?;
    let n_ops = ix(3)?;
    if n_theta + 1 > tape::MAX_VARS || n_ops > 64 {
        return None;
    }
    let mut at = 4usize;
    let mut ops = Vec::with_capacity(n_ops);
    for _ in 0..n_ops {
        let (op, len) = match g(at)? {
            1.0 => (Op::Turn { centre: ix(at + 1)?, ratio: ix(at + 2)?, phase: ix(at + 3)? }, 4),
            2.0 => (Op::Slide { line: ix(at + 1)?, advance: ix(at + 2)? }, 3),
            3.0 => (Op::Relative, 1),
            _ => return None,
        };
        ops.push(op);
        at += len;
    }
    let curve = if tool == Tool::Curve {
        let (n_t, lx, ly) = (ix(at)?, ix(at + 1)?, ix(at + 2)?);
        at += 3;
        let x = flat.get(at..at + lx)?;
        let y = flat.get(at + lx..at + lx + ly)?;
        at += lx + ly;
        let nv = ix(at)?;
        let values = flat.get(at + 1..at + 1 + nv)?;
        at += 1 + nv;
        if 1 + n_t + nv > tape::MAX_VARS {
            return None;
        }
        Some(CurveTool { n_theta: n_t, x, y, values, domain: (g(at)?, g(at + 1)?) })
    } else {
        None
    };
    let inner = if tool == Tool::Envelope {
        let (n_t, nv) = (ix(at)?, ix(at + 1)?);
        let values = flat.get(at + 2..at + 2 + nv)?;
        at += 2 + nv;
        let (anchor, from, to, len) = (g(at)?, g(at + 1)?, g(at + 2)?, ix(at + 3)?);
        let view = view(flat.get(at + 4..at + 4 + len)?)?;
        if !view.tool.analytic() || view.n_theta != n_t {
            return None;
        }
        Some(Box::new(InnerTool { view, values, anchor, domain: (from, to) }))
    } else {
        None
    };
    Some(View { n_theta, tool, side, ops, curve, inner })
}

/// The motion at the roll `t` (degrees, a jet), as `(Φ, d)`: `X = R(Φ)·T + d`.
fn motion(v: &View, outer: &[f64], t: Jet) -> Option<(Jet, [Jet; 2])> {
    let mut stack = [(Jet::default(), [Jet::default(); 2]); STACK];
    let mut depth = 0usize;
    let at = |i: usize| outer.get(i).copied();
    for op in &v.ops {
        let m = match *op {
            Op::Turn { centre, ratio, phase } => {
                let (cx, cy) = (at(centre)?, at(centre + 1)?);
                let phi = (t * (at(ratio)? * DEG)).shift(at(phase)?);
                let (sn, cs) = phi.sin_cos();
                // about the centre: R(c' − c) + c, so d = c − R c
                (phi, [Jet::constant(cx) - (cs * cx - sn * cy), Jet::constant(cy) - (sn * cx + cs * cy)])
            }
            Op::Slide { line, advance } => {
                let (ax, ay, bx, by) = (at(line)?, at(line + 1)?, at(line + 2)?, at(line + 3)?);
                let len = (bx - ax).dhypot(by - ay);
                if !(len > 0.0) {
                    return None;
                }
                // `advance` per whole turn of the roll
                let k = at(advance)? / 360.0 / len;
                (Jet::constant(0.0), [t * ((bx - ax) * k), t * ((by - ay) * k)])
            }
            Op::Relative => {
                if depth < 2 {
                    return None;
                }
                depth -= 2;
                let (src, obs) = (stack[depth], stack[depth + 1]);
                // observer⁻¹ ∘ source: the source as the observer sees it
                let (sn, cs) = (-obs.0).sin_cos();
                let (ox, oy) = (obs.1[0], obs.1[1]);
                let (sx, sy) = (src.1[0], src.1[1]);
                (src.0 - obs.0, [cs * (sx - ox) - sn * (sy - oy), sn * (sx - ox) + cs * (sy - oy)])
            }
        };
        if depth == STACK {
            return None;
        }
        stack[depth] = m;
        depth += 1;
    }
    (depth == 1).then_some(stack[0])
}

/// The motion about one roll at unit rate — what every evaluation at that roll shares: `Φ` and
/// `d` as series in `ε`, so the rate `ω` and the translation's rate `ḋ` are read off them.
#[derive(Clone, Copy)]
struct Pose {
    phi: Jet,
    d: [Jet; 2],
}

fn pose(v: &View, outer: &[f64], t: f64) -> Option<Pose> {
    let (phi, d) = motion(v, outer, Jet::var(t))?;
    Some(Pose { phi, d })
}

impl Pose {
    /// Where the instant centre stands, or `None` for a pure translation.
    fn instant_centre(&self) -> Option<(f64, f64)> {
        let omega = self.phi.0[1];
        if omega.abs() < 1e-15 {
            return None;
        }
        let (dx, dy) = (self.d[0].0[0], self.d[1].0[0]);
        let (vx, vy) = (self.d[0].0[1], self.d[1].0[1]);
        // ω J (I − d) + ḋ = 0
        Some((dx - vy / omega, dy + vx / omega))
    }
}

/// The tool at `s` (a jet): the point and its tangent `T'(s)`, in the tool's own placement.
fn tool(v: &View, outer: &[f64], s: Jet, ts: &mut tape::Scratch) -> Option<([Jet; 2], [Jet; 2])> {
    let th = |k: usize| outer.get(1 + k).copied();
    let delta = s.shift(-s.0[0]);
    // a series of derivatives at `s₀` read along `s(ε)`: the point and its tangent
    let along = |d: [[f64; 4]; 2]| {
        let p = d.map(|c| Jet::from_derivatives(&c).compose(delta));
        let t = d.map(|c| Jet::from_derivatives(&c[1..]).compose(delta));
        (p, t)
    };
    match v.tool {
        Tool::Point => {
            let z = Jet::constant(0.0);
            Some(([Jet::constant(th(0)?), Jet::constant(th(1)?)], [z, z]))
        }
        Tool::Line => {
            let (ax, ay, bx, by) = (th(0)?, th(1)?, th(2)?, th(3)?);
            let p = [(s * (bx - ax)).shift(ax), (s * (by - ay)).shift(ay)];
            Some((p, [Jet::constant(bx - ax), Jet::constant(by - ay)]))
        }
        Tool::Circle | Tool::Arc => {
            let r = if v.tool == Tool::Arc { th(6)? } else { th(2)? };
            let (cx, cy) = (th(0)?, th(1)?);
            let (sn, cs) = s.sin_cos();
            Some(([(cs * r).shift(cx), (sn * r).shift(cy)], [-(sn * r), cs * r]))
        }
        // its tapes' series in its own parameter, exact to the third
        Tool::Curve => {
            let c = v.curve.as_ref()?;
            let mut x = [0.0f64; tape::MAX_VARS];
            let n_vars = 1 + c.n_theta + c.values.len();
            x[0] = s.0[0];
            x[1..1 + c.n_theta].copy_from_slice(outer.get(1..1 + c.n_theta)?);
            x[1 + c.n_theta..n_vars].copy_from_slice(c.values);
            let sx = tape::eval_series_flat(c.x, n_vars, &x[..n_vars], ts);
            let sy = tape::eval_series_flat(c.y, n_vars, &x[..n_vars], ts);
            Some(along([sx.c, sy.c]))
        }
        // its Taylor series in its own roll, exact to the third (its tool being analytic)
        Tool::Envelope => {
            let e = v.inner.as_ref()?;
            let mut io = [0.0f64; OUTER_MAX];
            let io = outer_of(s.0[0], outer.get(1..1 + e.view.n_theta)?, e.values, &mut io)?;
            let si = carried(&e.view, io, s.0[0], e.anchor, ts, None)?;
            let o = orders(&e.view, io, s.0[0], si, 3, ts)?;
            Some(along([0, 1].map(|axis| o.c.map(|d| d[axis]))))
        }
    }
}

/// The tool's point at `s` carried to the roll `pose` stands at, and the envelope function
/// `F = X_s × X_t` there — along a path where `s` is the jet given and the roll is `t₀ + ε`
/// (`moving`) or held.
fn at(v: &View, outer: &[f64], pose: &Pose, moving: bool, s: Jet, ts: &mut tape::Scratch)
    -> Option<([Jet; 2], Jet)>
{
    let omega = pose.phi.0[1];
    let held = |j: Jet| Jet::constant(j.0[0]);
    let (phi, d, dd) = if moving {
        (pose.phi, pose.d, pose.d.map(Jet::derivative))
    } else {
        (held(pose.phi), pose.d.map(held), pose.d.map(|j| Jet::constant(j.0[1])))
    };
    let (p, tp) = tool(v, outer, s, ts)?;
    let (sn, cs) = phi.sin_cos();
    let x = [cs * p[0] - sn * p[1] + d[0], sn * p[0] + cs * p[1] + d[1]];
    let xs = [cs * tp[0] - sn * tp[1], sn * tp[0] + cs * tp[1]];
    // the velocity of the material point: ω J (X − d) + ḋ
    let vel = [-((x[1] - d[1]) * omega) + dd[0], (x[0] - d[0]) * omega + dd[1]];
    Some((x, xs[0] * vel[1] - xs[1] * vel[0]))
}

/// Newton on `F(s, t) = 0` in `s` from `s`, the roll held at `pose`'s.
fn root(v: &View, outer: &[f64], pose: &Pose, mut s: f64, ts: &mut tape::Scratch) -> Option<f64> {
    for _ in 0..NEWTON_MAX {
        let (_, f) = at(v, outer, pose, false, Jet::var(s), ts)?;
        let (r, rs) = (f.0[0], f.0[1]);
        if !(rs != 0.0) || !r.is_finite() {
            return None;
        }
        let step = r / rs;
        s -= step;
        if step.abs() <= 1e-14 * (1.0 + s.abs()) {
            return s.is_finite().then_some(s);
        }
    }
    let (_, f) = at(v, outer, pose, false, Jet::constant(s), ts)?;
    (f.0[0].abs() <= 1e-10 * (1.0 + s.abs())).then_some(s)
}

/// Where to start the root at roll `t`, chosen by `side`: a line's anywhere, a circle's on the
/// line from its centre through the instant centre (exact), a curve tool's from a scan of its
/// interval.
fn chosen(v: &View, outer: &[f64], pose: &Pose, ts: &mut tape::Scratch) -> Option<f64> {
    match v.tool {
        Tool::Point | Tool::Line => return Some(0.0),
        Tool::Circle | Tool::Arc => {
            let (cx, cy) = (outer.get(1).copied()?, outer.get(2).copied()?);
            let (sn, cs) = (pose.phi.0[0].dsin(), pose.phi.0[0].dcos());
            let (px, py) = (cs * cx - sn * cy + pose.d[0].0[0], sn * cx + cs * cy + pose.d[1].0[0]);
            // toward the instant centre; for a slide, square to the velocity
            let (wx, wy) = match pose.instant_centre() {
                Some((ix, iy)) => (ix - px, iy - py),
                None => (-pose.d[1].0[1], pose.d[0].0[1]),
            };
            let (wx, wy) = (wx * v.side, wy * v.side);
            // back into the tool's own placement
            return Some((cs * wy - sn * wx).datan2(cs * wx + sn * wy));
        }
        Tool::Curve | Tool::Envelope => {}
    }
    let (a, b) = v.tool_domain()?;
    let mut roots: Vec<f64> = Vec::new();
    let mut prev: Option<(f64, f64)> = None;
    for k in 0..=SCAN {
        let s = a + (b - a) * k as f64 / SCAN as f64;
        let Some((_, f)) = at(v, outer, pose, false, Jet::constant(s), ts) else { continue };
        let f = f.0[0];
        if let Some((sp, fp)) = prev {
            if fp == 0.0 || fp.signum() != f.signum() {
                if let Some(r) = root(v, outer, pose, 0.5 * (sp + s), ts) {
                    if !roots.iter().any(|q| (q - r).abs() < 1e-9 * (b - a).abs()) {
                        roots.push(r);
                    }
                }
            }
        }
        prev = Some((s, f));
    }
    let centre = pose.instant_centre();
    let mut best: Option<(f64, f64)> = None;
    for r in roots {
        let Some((x, _)) = at(v, outer, pose, false, Jet::constant(r), ts) else { continue };
        let key = v.side * match centre {
            Some((ix, iy)) => (x[0].0[0] - ix).dhypot(x[1].0[0] - iy),
            None => r,
        };
        if best.is_none_or(|(k, _)| key < k) {
            best = Some((key, r));
        }
    }
    best.map(|(_, r)| r)
}

/// The root at roll `t`: for a curve tool chosen at the anchor and carried there by continuity
/// (resumed from `from`, where this contact last was, when that is near); for a point, line,
/// circle or arc, whose roots have no branches to lose, chosen in place.
fn carried(v: &View, outer: &[f64], t: f64, anchor: f64, ts: &mut tape::Scratch, from: Option<(f64, f64)>)
    -> Option<f64>
{
    if v.tool == Tool::Point {
        return Some(0.0);
    }
    let here = pose(v, outer, t)?;
    if v.tool.analytic() {
        let s = chosen(v, outer, &here, ts)?;
        return root(v, outer, &here, s, ts);
    }
    if let Some((tp, sp)) = from {
        let (a, b) = v.tool_domain()?;
        if (t - tp).abs() <= 1e-3 * (1.0 + t.abs()) {
            if let Some(s) = root(v, outer, &here, sp, ts) {
                if (s - sp).abs() <= 0.05 * (b - a).abs() {
                    return Some(s);
                }
            }
        }
    }
    let mut s = chosen(v, outer, &pose(v, outer, anchor)?, ts)?;
    if t != anchor {
        for k in 1..=MARCH {
            let tk = anchor + (t - anchor) * k as f64 / MARCH as f64;
            s = root(v, outer, &pose(v, outer, tk)?, s, ts)?;
        }
    }
    Some(s)
}

/// What one evaluation came to: `C` and its derivatives in the roll (NaN past what was asked or
/// is exact), and the root.
#[derive(Clone, Copy, Debug)]
struct Orders {
    c: [[f64; 2]; 4],
    s: f64,
}

/// `C` to its `need`-th derivative (1 to 3) at roll `t`, the root `s0` already found — capped at
/// the second for a curve tool, whose third would read its tool's fourth.
fn orders(v: &View, outer: &[f64], t: f64, s0: f64, need: usize, ts: &mut tape::Scratch) -> Option<Orders> {
    let here = pose(v, outer, t)?;
    let top = if v.tool.analytic() { need.min(3) } else { need.min(2) };
    let x = if v.tool == Tool::Point {
        at(v, outer, &here, true, Jet::constant(0.0), ts)?.0
    } else {
        let (_, fs) = at(v, outer, &here, false, Jet::var(s0), ts)?;
        let f_s = fs.0[1];
        if !(f_s != 0.0) {
            return None;
        }
        // each order of the root, one division by F_s with the order itself not yet known
        let mut s = Jet::constant(s0);
        for k in 1..=top {
            let (_, f) = at(v, outer, &here, true, s, ts)?;
            s.0[k] = -f.0[k] / f_s;
        }
        at(v, outer, &here, true, s, ts)?.0
    };
    let c = std::array::from_fn(|k| if k <= top { [x[0].nth(k), x[1].nth(k)] } else { [f64::NAN; 2] });
    Some(Orders { c, s: s0 })
}

/// The memory of where each contact's root last was, keyed by where its constants live — the
/// trace's `Seen`, for a curve tool's continuation.
const SEEN_MAX: usize = 4096;

thread_local! {
    static SEEN: std::cell::RefCell<std::collections::BTreeMap<(usize, usize), (f64, f64)>> =
        std::cell::RefCell::new(std::collections::BTreeMap::new());
    static SCRATCH: std::cell::RefCell<tape::Scratch> = std::cell::RefCell::new(tape::Scratch::new());
}

/// Forget every remembered root — `System::new` calls it, as it calls `locus::forget`.
pub fn forget() {
    SEEN.with(|s| s.borrow_mut().clear());
}

/// A contact's constants read once: `[anchor, n_values, values…, flat…]` and the roll and
/// columns it is asked at.
struct Read<'a> {
    v: View<'a>,
    anchor: f64,
    outer: [f64; OUTER_MAX],
    width: usize,
    key: (usize, usize),
}

fn read<'a>(consts: &'a [f64], u: f64, theta: &[f64]) -> Option<Read<'a>> {
    let (anchor, values, flat) = contact_prefix(consts, OUTER_MAX)?;
    let mut outer = [0.0f64; OUTER_MAX];
    let width = outer_of(u, theta, values, &mut outer)?.len();
    Some(Read { v: view(flat)?, anchor, outer, width, key: key_of(flat) })
}

impl Read<'_> {
    fn outer(&self) -> &[f64] {
        &self.outer[..self.width]
    }

    /// The value and orders at this roll, the root carried from what this contact saw last.
    fn centre(&self, need: usize, ts: &mut tape::Scratch) -> Option<Orders> {
        let t = self.outer[0];
        let from = SEEN.with(|s| s.borrow().get(&self.key).copied());
        let s0 = carried(&self.v, self.outer(), t, self.anchor, ts, from)?;
        let o = orders(&self.v, self.outer(), t, s0, need, ts)?;
        SEEN.with(|s| {
            let mut s = s.borrow_mut();
            if s.len() >= SEEN_MAX {
                s.clear();
            }
            s.insert(self.key, (t, s0));
        });
        Some(o)
    }

    /// `C'''` where `orders` could not read it exactly: a central difference of the exact `C''`
    /// along the roll — read only by a curvature's Jacobian.
    fn third(&self, o: &Orders, ts: &mut tape::Scratch) -> Option<[f64; 2]> {
        if o.c[3].iter().all(|x| x.is_finite()) {
            return Some(o.c[3]);
        }
        let t = self.outer[0];
        let h = 1e-3 * (1.0 + t.abs());
        let mut probe = self.outer;
        let mut c2 = |t: f64, ts: &mut tape::Scratch| -> Option<[f64; 2]> {
            probe[0] = t;
            let p = &probe[..self.width];
            let s = carried(&self.v, p, t, self.anchor, ts, Some((self.outer[0], o.s)))?;
            Some(orders(&self.v, p, t, s, 2, ts)?.c[2])
        };
        let (p, m) = (c2(t + h, ts)?, c2(t - h, ts)?);
        Some([(p[0] - m[0]) / (2.0 * h), (p[1] - m[1]) / (2.0 * h)])
    }

    /// Central differences of `C` to its `upto`-th derivative along each column, the root
    /// carried from the centre's: `g[k][axis][j]`.  Central and not forward: a claim is judged by
    /// the rank of a Jacobian these gradients sit in, and a forward difference's error made an
    /// implied row read as independent.
    fn gradients(&self, o: &Orders, upto: usize, ts: &mut tape::Scratch) -> Option<[[[f64; tape::MAX_VARS]; 2]; 3]> {
        let mut g = [[[0.0f64; tape::MAX_VARS]; 2]; 3];
        let mut probe = self.outer;
        let t = self.outer[0];
        for j in 0..self.v.n_theta {
            let i = 1 + j;
            let h = 1e-5 * self.outer[i].abs().max(1.0);
            let mut side = |x: f64, ts: &mut tape::Scratch| -> Option<Orders> {
                probe[i] = x;
                let p = &probe[..self.width];
                let s = if self.v.tool.analytic() {
                    carried(&self.v, p, t, self.anchor, ts, None)
                } else {
                    root(&self.v, p, &pose(&self.v, p, t)?, o.s, ts)
                };
                let q = s.and_then(|s| orders(&self.v, p, t, s, upto, ts));
                probe[i] = self.outer[i];
                q
            };
            let (up, down) = (side(self.outer[i] + h, ts)?, side(self.outer[i] - h, ts)?);
            for k in 0..=upto {
                for axis in 0..2 {
                    g[k][axis][j] = (up.c[k][axis] - down.c[k][axis]) / (2.0 * h);
                }
            }
        }
        Some(g)
    }
}

/// The evaluation a contact kernel makes: `consts` its constants, `u` the roll and `theta` the
/// curve's columns.  `C'` in `dx[0]` and the orders to `need`; the gradient along the columns,
/// a central difference, in `dx[1..]` when `gradient` is asked.
pub fn kernel_eval(consts: &[f64], u: f64, theta: &[f64], need: u8, gradient: bool) -> Val {
    let mut val = Val::default();
    let Some(r) = read(consts, u, theta) else { return val };
    SCRATCH.with(|ts| {
        let ts = &mut *ts.borrow_mut();
        let Some(o) = r.centre(usize::from(need), ts) else { return };
        fill(&mut val, &r, &o, need, ts);
        if gradient {
            match r.gradients(&o, 0, ts) {
                Some(g) => {
                    val.dx[1..1 + theta.len()].copy_from_slice(&g[0][0][..theta.len()]);
                    val.dy[1..1 + theta.len()].copy_from_slice(&g[0][1][..theta.len()]);
                }
                None => val.ok = false,
            }
        }
    });
    val
}

/// `val` from what one evaluation came to: the point, `C'`, and the orders asked for.
fn fill(val: &mut Val, r: &Read, o: &Orders, need: u8, ts: &mut tape::Scratch) {
    val.x = o.c[0][0];
    val.y = o.c[0][1];
    val.dx[0] = o.c[1][0];
    val.dy[0] = o.c[1][1];
    val.ok = true;
    val.orders = 1;
    if need >= 2 && o.c[2].iter().all(|x| x.is_finite()) {
        val.d2 = o.c[2];
        val.orders = 2;
        if need >= 3 {
            if let Some(d3) = r.third(o, ts).filter(|d| d.iter().all(|x| x.is_finite())) {
                val.d3 = d3;
                val.orders = 3;
            }
        }
    }
}

/// The frame a tangency's (`need` 2) or a curvature's (`need` 3) Jacobian reads: the value, its
/// gradient, and the gradients of `C'` and `C''` along `[u, θ…]` — along `u` the next order,
/// along the columns a difference, one sweep of them for all three.
pub fn kernel_frame(consts: &[f64], u: f64, theta: &[f64], need: u8) -> Frame {
    let mut val = Val::default();
    let mut d1 = [[f64::NAN; tape::MAX_VARS]; 2];
    let mut d2 = [[f64::NAN; tape::MAX_VARS]; 2];
    let Some(r) = read(consts, u, theta) else { return Frame { val, d1, d2 } };
    SCRATCH.with(|ts| {
        let ts = &mut *ts.borrow_mut();
        let Some(o) = r.centre(usize::from(need), ts) else { return };
        fill(&mut val, &r, &o, need, ts);
        let Some(g) = r.gradients(&o, usize::from(need - 1), ts) else {
            val.ok = false;
            return;
        };
        val.dx[1..1 + theta.len()].copy_from_slice(&g[0][0][..theta.len()]);
        val.dy[1..1 + theta.len()].copy_from_slice(&g[0][1][..theta.len()]);
        for axis in 0..2 {
            d1[axis][0] = val.d2[axis];
            d2[axis][0] = val.d3[axis];
            for j in 0..theta.len() {
                d1[axis][1 + j] = g[1][axis][j];
                if need >= 3 {
                    d2[axis][1 + j] = g[2][axis][j];
                }
            }
        }
    });
    Frame { val, d1, d2 }
}

/// The curve over `[a, b]` as `n` chords — what the polyline draws.
pub fn sweep(flat: &[f64], outer: &[f64], anchor: f64, a: f64, b: f64, n: usize) -> Vec<(f64, f64)> {
    let Some(v) = view(flat) else { return Vec::new() };
    SCRATCH.with(|ts| {
        let ts = &mut *ts.borrow_mut();
        let mut out = Vec::with_capacity(n + 1);
        let mut probe = outer.to_vec();
        let mut last: Option<(f64, f64)> = None;
        let mut point = (f64::NAN, f64::NAN);
        for k in 0..=n {
            let t = a + (b - a) * k as f64 / n.max(1) as f64;
            probe[0] = t;
            if let Some(s) = carried(&v, &probe, t, anchor, ts, last) {
                if let Some(o) = orders(&v, &probe, t, s, 1, ts) {
                    point = (o.c[0][0], o.c[0][1]);
                    last = Some((t, s));
                }
            }
            out.push(point);
        }
        out
    })
}

/// What a generated profile comes to at one roll, read where no contact asks (a sheet built from
/// the curve, `brep::sweep::extruded`): its point and its first two derivatives along the roll
/// (per degree), exact for a point, line, circle or arc, and the tool's parameter cutting there.
#[derive(Clone, Copy, Debug)]
pub struct Cut {
    pub c: [f64; 2],
    pub dc: [f64; 2],
    pub ddc: [f64; 2],
    pub s: f64,
}

/// The profile at roll `outer[0]`, cold: `None` where no root is found.
pub fn cut_at(flat: &[f64], outer: &[f64], anchor: f64) -> Option<Cut> {
    let v = view(flat)?;
    SCRATCH.with(|ts| {
        let ts = &mut *ts.borrow_mut();
        let s = carried(&v, outer, outer[0], anchor, ts, None)?;
        let o = orders(&v, outer, outer[0], s, 2, ts)?;
        Some(Cut { c: o.c[0], dc: o.c[1], ddc: o.c[2], s })
    })
}

/// Where the curve is at roll `t`, cold.
pub fn point(flat: &[f64], outer: &[f64], anchor: f64) -> (f64, f64) {
    let Some(v) = view(flat) else { return (f64::NAN, f64::NAN) };
    SCRATCH.with(|ts| {
        let ts = &mut *ts.borrow_mut();
        carried(&v, outer, outer[0], anchor, ts, None)
            .and_then(|s| orders(&v, outer, outer[0], s, 1, ts))
            .map_or((f64::NAN, f64::NAN), |o| (o.c[0][0], o.c[0][1]))
    })
}
