//! A profile **generated by a motion in the plane**: the envelope of a tool carried by a planar
//! motion, as a curve of the drawing (issue #61, proposal 2; spec §6.15.1).
//!
//! `cut := envelope(tool, under: m, from: a, to: b)` with `tool` a point, line, circle or curve
//! of the sheet and `m` a planar motion (`motion(about: point, …)`, `motion(along: line, …)`,
//! `motion(of: …, relative_to: …)`) is the curve `C(t)`, `t` the roll in degrees: the point of
//! the tool at roll `t` where the tool is cutting.  The tool is drawn where it stands at roll 0;
//! the motion carries it to `X(s, t) = M(t)·T(s)`, `s` the tool's own parameter, and the cutting
//! point is where the tool's tangent runs along the velocity of the material point under it,
//! `F(s, t) = X_s × X_t = 0` — the envelope condition `n · v = 0`, which in the plane says the
//! normal passes through the instant centre.  One scalar unknown, `s`, per roll.
//!
//! The motion's numbers and the tool's are the curve's **columns** — the centres it turns about,
//! the line it slides along, the tool's own coordinates — so a contact against a generated
//! profile moves the tool and the motion to suit, which is what synthesising a conjugate means.
//!
//! **Exact orders.**  `C`, `C'` and `C''` are read along `t + ε` in Taylor arithmetic
//! (`taylor::Jet`): the root `s(ε)` order by order, each one division by `F_s` (the scalar
//! implicit function theorem, Wagner–Walther–Schaefer once more), then `X(s(ε), t + ε)`.  `C'''`
//! would need the tool's fourth derivative, so it and every gradient along the columns are
//! differences — read only by Jacobians, never by a residual.
//!
//! **Which root.**  A line tool cuts once; a circle twice, on the line from its centre through
//! the instant centre: `side` says which, the point nearer the instant centre (`near`, a roller's
//! working side) or the farther.  A curve tool may cut in several places: the roots at the
//! anchor roll are found by a scan of the tool's interval, `side` picks among them, and the
//! choice is carried by continuity to every other roll, as a trace carries its branch.

#[allow(unused_imports)]
use crate::fmath::Det;
use crate::taylor::Jet;
use crate::tape;

/// The tool's kind, as the encoding names it.
pub const TOOL_POINT: f64 = 0.0;
pub const TOOL_LINE: f64 = 1.0;
pub const TOOL_CIRCLE: f64 = 2.0;
pub const TOOL_CURVE: f64 = 3.0;
/// An arc cuts as its circle does; its radius is its seventh column.
pub const TOOL_ARC: f64 = 4.0;
/// A profile generated by an analytic tool, cutting in its turn — a rack-cut tooth cutting its
/// mate.  Its columns are its own (its tool's and its motion's).
pub const TOOL_ENVELOPE: f64 = 5.0;

/// The motion's postfix program: a turn about a centre at a ratio and phase, a slide along a
/// line by an advance per turn, and the relative of two (`of` the first, `relative_to` the
/// second).
pub const OP_TURN: f64 = 1.0;
pub const OP_SLIDE: f64 = 2.0;
pub const OP_RELATIVE: f64 = 3.0;

const DEG: f64 = std::f64::consts::PI / 180.0;
/// The widest outer vector `[t, θ…, values…]`: the columns are held to `tape::MAX_VARS` (a
/// contact's gradient is that wide), the motion's numbers, constants, ride past them.
pub const OUTER_MAX: usize = 2 * tape::MAX_VARS;
const NEWTON_MAX: usize = 40;
/// Samples of a curve tool's interval when its roots are looked for at the anchor.
const SCAN: usize = 128;
/// Continuation steps from the anchor roll to the one asked for, for a curve tool.
const MARCH: usize = 32;

/// A compiled generated profile, held as its encoding — what rides in a contact's constants:
/// `[n_theta, tool, side, n_ops, ops…, tool extra…]`.  `ops` index the outer vector
/// `[t, θ…, values…]` directly: a turn is `[OP_TURN, centre, ratio, phase]` (the centre's x,
/// then two value slots, the phase in radians), a slide `[OP_SLIDE, line, advance]` (the line's
/// first x), a relative `[OP_RELATIVE]`.  The tool's columns start at 1.  A curve tool carries
/// `[n_vars, n_tool_theta, lx, ly, x…, y…, n_tool_values, tool values…, from, to]` after.
#[derive(Clone, Debug)]
pub struct Generated {
    pub flat: Vec<f64>,
}

/// The flat form, read.
struct View<'a> {
    n_theta: usize,
    tool: f64,
    side: f64,
    ops: Vec<&'a [f64]>,
    curve: Option<CurveTool<'a>>,
    inner: Option<Box<InnerTool<'a>>>,
}

/// A generated tool: its own encoding, the numbers its motion was given, the roll it is
/// anchored at and its interval.
struct InnerTool<'a> {
    view: View<'a>,
    n_theta: usize,
    values: &'a [f64],
    anchor: f64,
    domain: (f64, f64),
}

/// Whether the tool is a line, circle, arc or point: exact at every order, so the root and the
/// cut are too, to the third (`orders`).
fn analytic(v: &View) -> bool {
    v.tool != TOOL_CURVE && v.tool != TOOL_ENVELOPE
}

/// The interval a curve or generated tool runs over — where its cuts are looked for.
fn tool_domain(v: &View) -> Option<(f64, f64)> {
    match (&v.curve, &v.inner) {
        (Some(c), _) => Some(c.domain),
        (_, Some(e)) => Some(e.domain),
        _ => None,
    }
}

struct CurveTool<'a> {
    n_vars: usize,
    n_theta: usize,
    x: &'a [f64],
    y: &'a [f64],
    values: &'a [f64],
    domain: (f64, f64),
}

fn view(flat: &[f64]) -> Option<View<'_>> {
    let g = |i: usize| flat.get(i).copied().filter(|v| v.is_finite());
    let n_theta = g(0)? as usize;
    let tool = g(1)?;
    let side = g(2)?;
    let n_ops = g(3)? as usize;
    if n_theta + 1 > tape::MAX_VARS || n_ops > 64 {
        return None;
    }
    let mut at = 4usize;
    let mut ops = Vec::with_capacity(n_ops);
    for _ in 0..n_ops {
        let len = match g(at)? {
            OP_TURN => 4,
            OP_SLIDE => 3,
            OP_RELATIVE => 1,
            _ => return None,
        };
        ops.push(flat.get(at..at + len)?);
        at += len;
    }
    let curve = if tool == TOOL_CURVE {
        let n_vars = g(at)? as usize;
        let n_t = g(at + 1)? as usize;
        let (lx, ly) = (g(at + 2)? as usize, g(at + 3)? as usize);
        at += 4;
        let x = flat.get(at..at + lx)?;
        let y = flat.get(at + lx..at + lx + ly)?;
        at += lx + ly;
        let nv = g(at)? as usize;
        let values = flat.get(at + 1..at + 1 + nv)?;
        at += 1 + nv;
        let domain = (g(at)?, g(at + 1)?);
        if n_vars > tape::MAX_VARS || 1 + n_t + nv != n_vars {
            return None;
        }
        Some(CurveTool { n_vars, n_theta: n_t, x, y, values, domain })
    } else {
        None
    };
    // `[n_tool_theta, n_values, values…, anchor, from, to, len, flat…]`
    let inner = if tool == TOOL_ENVELOPE {
        let n_t = g(at)? as usize;
        let nv = g(at + 1)? as usize;
        let values = flat.get(at + 2..at + 2 + nv)?;
        at += 2 + nv;
        let (anchor, from, to, len) = (g(at)?, g(at + 1)?, g(at + 2)?, g(at + 3)? as usize);
        let view = view(flat.get(at + 4..at + 4 + len)?)?;
        if !analytic(&view) || view.n_theta != n_t {
            return None;
        }
        Some(Box::new(InnerTool { view, n_theta: n_t, values, anchor, domain: (from, to) }))
    } else {
        None
    };
    Some(View { n_theta, tool, side, ops, curve, inner })
}

/// The motion at the roll `t` (degrees, a jet), as `(Φ, d)`: `X = R(Φ)·T + d`.
fn motion(v: &View, outer: &[f64], t: Jet) -> Option<(Jet, [Jet; 2])> {
    let mut stack: Vec<(Jet, [Jet; 2])> = Vec::with_capacity(4);
    for op in &v.ops {
        let o = |k: usize| outer.get(op[k] as usize).copied();
        if op[0] == OP_TURN {
            let (cx, cy) = (o(1)?, outer.get(op[1] as usize + 1).copied()?);
            let (ratio, phase) = (o(2)?, o(3)?);
            let phi = (t * (ratio * DEG)).shift(phase);
            let (sn, cs) = phi.sin_cos();
            // about the centre: R(c' − c) + c, so d = c − R c
            let d = [
                Jet::constant(cx) - (cs * cx - sn * cy),
                Jet::constant(cy) - (sn * cx + cs * cy),
            ];
            stack.push((phi, d));
        } else if op[0] == OP_SLIDE {
            let a = op[1] as usize;
            let (ax, ay, bx, by) = (
                outer.get(a).copied()?,
                outer.get(a + 1).copied()?,
                outer.get(a + 2).copied()?,
                outer.get(a + 3).copied()?,
            );
            let advance = o(2)?;
            let len = (bx - ax).dhypot(by - ay);
            if !(len > 0.0) {
                return None;
            }
            // `advance` per whole turn of the roll
            let k = advance / 360.0 / len;
            stack.push((Jet::constant(0.0), [t * ((bx - ax) * k), t * ((by - ay) * k)]));
        } else {
            let obs = stack.pop()?;
            let src = stack.pop()?;
            // observer⁻¹ ∘ source: the source as the observer sees it
            let (sn, cs) = (-obs.0).sin_cos();
            let (ox, oy) = (obs.1[0], obs.1[1]);
            let inv = [-(cs * ox - sn * oy), -(sn * ox + cs * oy)];
            let (sx, sy) = (src.1[0], src.1[1]);
            let d = [cs * sx - sn * sy + inv[0], sn * sx + cs * sy + inv[1]];
            stack.push((src.0 - obs.0, d));
        }
    }
    let m = stack.pop()?;
    stack.is_empty().then_some(m)
}

/// The tool at `s` (a jet): the point and its tangent `T'(s)`, in the tool's own placement.
fn tool(v: &View, outer: &[f64], s: Jet, ts: &mut tape::Scratch) -> Option<([Jet; 2], [Jet; 2])> {
    let th = |k: usize| outer.get(1 + k).copied();
    if v.tool == TOOL_POINT {
        let z = Jet::constant(0.0);
        return Some(([Jet::constant(th(0)?), Jet::constant(th(1)?)], [z, z]));
    }
    if v.tool == TOOL_LINE {
        let (ax, ay, bx, by) = (th(0)?, th(1)?, th(2)?, th(3)?);
        let p = [(s * (bx - ax)).shift(ax), (s * (by - ay)).shift(ay)];
        return Some((p, [Jet::constant(bx - ax), Jet::constant(by - ay)]));
    }
    if v.tool == TOOL_CIRCLE || v.tool == TOOL_ARC {
        let r = if v.tool == TOOL_ARC { th(6)? } else { th(2)? };
        let (cx, cy) = (th(0)?, th(1)?);
        let (sn, cs) = s.sin_cos();
        return Some(([(cs * r).shift(cx), (sn * r).shift(cy)], [-(sn * r), cs * r]));
    }
    // a generated tool: its Taylor series at `s₀` in its own roll, exact to the third
    // (`orders` over an analytic tool), composed with the parameter's path
    if let Some(e) = v.inner.as_ref() {
        let mut io = [0.0f64; OUTER_MAX];
        let width = 1 + e.n_theta + e.values.len();
        io[0] = s.0[0];
        for k in 0..e.n_theta {
            io[1 + k] = th(k)?;
        }
        io[1 + e.n_theta..width].copy_from_slice(e.values);
        let io = &io[..width];
        let si = carried(&e.view, io, s.0[0], e.anchor, ts, None)?;
        let o = orders(&e.view, io, s.0[0], si, true, ts)?;
        let coef = |axis: usize| [o.c[0][axis], o.c[1][axis], o.c[2][axis] / 2.0, o.c[3][axis] / 6.0];
        let delta = s.shift(-s.0[0]);
        let compose = |c: [f64; 4], derivative: bool| {
            let mut out = Jet::constant(if derivative { c[1] } else { c[0] });
            let mut pow = Jet::constant(1.0);
            for k in 1..if derivative { 3 } else { 4 } {
                pow = pow * delta;
                out = out + pow * if derivative { (k + 1) as f64 * c[k + 1] } else { c[k] };
            }
            out
        };
        let (cx, cy) = (coef(0), coef(1));
        return Some(([compose(cx, false), compose(cy, false)], [compose(cx, true), compose(cy, true)]));
    }
    let c = v.curve.as_ref()?;
    // the tool's own variables: its parameter, its columns, its constants
    let mut x = [0.0f64; OUTER_MAX];
    x[0] = s.0[0];
    for k in 0..c.n_theta {
        x[1 + k] = th(k)?;
    }
    x[1 + c.n_theta..c.n_vars].copy_from_slice(c.values);
    let sx = tape::eval_series_flat(c.x, c.n_vars, &x[..c.n_vars], ts);
    let sy = tape::eval_series_flat(c.y, c.n_vars, &x[..c.n_vars], ts);
    // composed with the parameter's path: Σ cₖ δᵏ / k!, δ = s − s₀ (no constant term)
    let delta = s.shift(-s.0[0]);
    let compose = |c: &[f64; 4], from: usize| {
        let mut out = Jet::constant(c[from]);
        let mut pow = Jet::constant(1.0);
        let mut fact = 1.0;
        for k in 1..4 - from {
            pow = pow * delta;
            fact *= k as f64;
            out = out + pow * (c[from + k] / fact);
        }
        out
    };
    Some(([compose(&sx.c, 0), compose(&sy.c, 0)], [compose(&sx.c, 1), compose(&sy.c, 1)]))
}

/// The tool's point at `s` carried to roll `t`, and the envelope function `F = X_s × X_t`
/// there — along a path where `s` is the jet given and the roll is `t₀ + ε` (`moving`) or held.
fn at(
    v: &View,
    outer: &[f64],
    t0: f64,
    moving: bool,
    s: Jet,
    ts: &mut tape::Scratch,
) -> Option<([Jet; 2], Jet)> {
    // the motion at unit rate: its own rate and the rate of its translation, whichever path
    let (phi_u, d_u) = motion(v, outer, Jet::var(t0))?;
    let omega = phi_u.0[1];
    let (phi, d, dd) = if moving {
        (phi_u, d_u, [d_u[0].rate(), d_u[1].rate()])
    } else {
        let c = |j: Jet| Jet::constant(j.0[0]);
        (c(phi_u), [c(d_u[0]), c(d_u[1])], [Jet::constant(d_u[0].0[1]), Jet::constant(d_u[1].0[1])])
    };
    let (p, tp) = tool(v, outer, s, ts)?;
    let (sn, cs) = phi.sin_cos();
    let x = [cs * p[0] - sn * p[1] + d[0], sn * p[0] + cs * p[1] + d[1]];
    let xs = [cs * tp[0] - sn * tp[1], sn * tp[0] + cs * tp[1]];
    // the velocity of the material point: ω J (X − d) + ḋ
    let vel = [-((x[1] - d[1]) * omega) + dd[0], (x[0] - d[0]) * omega + dd[1]];
    Some((x, xs[0] * vel[1] - xs[1] * vel[0]))
}

/// Newton on `F(s, t) = 0` in `s` from `s`, the roll held.
fn root(v: &View, outer: &[f64], t: f64, mut s: f64, ts: &mut tape::Scratch) -> Option<f64> {
    for _ in 0..NEWTON_MAX {
        let (_, f) = at(v, outer, t, false, Jet::var(s), ts)?;
        let (r, rs) = (f.0[0], f.0[1]);
        if !(rs != 0.0) || !r.is_finite() {
            return None;
        }
        let step = r / rs;
        s -= step;
        if step.abs() <= 1e-14 * (1.0 + s.abs()) {
            return s.is_finite().then_some(s);
        }
    }
    let (_, f) = at(v, outer, t, false, Jet::constant(s), ts)?;
    (f.0[0].abs() <= 1e-10 * (1.0 + s.abs())).then_some(s)
}

/// Where the instant centre stands at roll `t`, or `None` for a pure translation.
fn instant_centre(v: &View, outer: &[f64], t: f64) -> Option<(f64, f64)> {
    let (phi, d) = motion(v, outer, Jet::var(t))?;
    let omega = phi.0[1];
    if omega.abs() < 1e-15 {
        return None;
    }
    let (dx, dy) = (d[0].0[0], d[1].0[0]);
    let (vx, vy) = (d[0].0[1], d[1].0[1]);
    // ω J (I − d) + ḋ = 0
    Some((dx - vy / omega, dy + vx / omega))
}

/// The root at roll `t` chosen by `side`, from nothing: a line's one, a circle's on the line
/// through the instant centre, a curve tool's from a scan of its interval.  `None` for a point,
/// which has no parameter.
fn chosen(v: &View, outer: &[f64], t: f64, ts: &mut tape::Scratch) -> Option<f64> {
    if v.tool == TOOL_POINT {
        return Some(0.0);
    }
    if v.tool == TOOL_LINE {
        return root(v, outer, t, 0.0, ts);
    }
    let pose = |s: f64, ts: &mut tape::Scratch| at(v, outer, t, false, Jet::constant(s), ts);
    if v.tool == TOOL_CIRCLE || v.tool == TOOL_ARC {
        let (cx, cy) = (outer.get(1).copied()?, outer.get(2).copied()?);
        let (phi, d) = motion(v, outer, Jet::constant(t))?;
        let (sn, cs) = (phi.0[0].dsin(), phi.0[0].dcos());
        let (px, py) = (cs * cx - sn * cy + d[0].0[0], sn * cx + cs * cy + d[1].0[0]);
        // toward the instant centre; for a slide, square to the velocity
        let (wx, wy) = match instant_centre(v, outer, t) {
            Some((ix, iy)) => (ix - px, iy - py),
            None => {
                let (_, du) = motion(v, outer, Jet::var(t))?;
                (-du[1].0[1], du[0].0[1])
            }
        };
        let (wx, wy) = (wx * v.side, wy * v.side);
        // back into the tool's own placement
        return Some((cs * wy - sn * wx).datan2(cs * wx + sn * wy));
    }
    let (a, b) = tool_domain(v)?;
    let mut roots: Vec<f64> = Vec::new();
    let mut prev: Option<(f64, f64)> = None;
    for k in 0..=SCAN {
        let s = a + (b - a) * k as f64 / SCAN as f64;
        let Some((_, f)) = pose(s, ts) else { continue };
        let f = f.0[0];
        if let Some((sp, fp)) = prev {
            if fp == 0.0 || fp.signum() != f.signum() {
                if let Some(r) = root(v, outer, t, 0.5 * (sp + s), ts) {
                    if !roots.iter().any(|q| (q - r).abs() < 1e-9 * (b - a).abs()) {
                        roots.push(r);
                    }
                }
            }
        }
        prev = Some((s, f));
    }
    let centre = instant_centre(v, outer, t);
    let dist = |s: f64, ts: &mut tape::Scratch| -> f64 {
        let Some((x, _)) = pose(s, ts) else { return f64::INFINITY };
        match centre {
            Some((ix, iy)) => (x[0].0[0] - ix).dhypot(x[1].0[0] - iy),
            None => s,
        }
    };
    let mut best: Option<(f64, f64)> = None;
    for r in roots {
        let key = v.side * dist(r, ts);
        if best.is_none_or(|(k, _)| key < k) {
            best = Some((key, r));
        }
    }
    best.map(|(_, r)| r)
}

/// The root at roll `t`: chosen at the anchor and carried there by continuity, or — for a line,
/// a circle, a point, whose roots have no branches to lose — chosen in place.
fn carried(
    v: &View,
    outer: &[f64],
    t: f64,
    anchor: f64,
    ts: &mut tape::Scratch,
    from: Option<(f64, f64)>,
) -> Option<f64> {
    if analytic(v) {
        let s = chosen(v, outer, t, ts)?;
        return if v.tool == TOOL_POINT { Some(s) } else { root(v, outer, t, s, ts) };
    }
    // a pose already carried near here is the continuation's next step
    if let Some((tp, sp)) = from {
        let (a, b) = tool_domain(v)?;
        let span = (b - a).abs();
        if (t - tp).abs() <= 1e-3 * (1.0 + t.abs()) {
            if let Some(s) = root(v, outer, t, sp, ts) {
                if (s - sp).abs() <= 0.05 * span {
                    return Some(s);
                }
            }
        }
    }
    let mut s = chosen(v, outer, anchor, ts)?;
    if t != anchor {
        for k in 1..=MARCH {
            let tk = anchor + (t - anchor) * k as f64 / MARCH as f64;
            s = root(v, outer, tk, s, ts)?;
        }
    }
    Some(s)
}

/// What one evaluation came to: `C`, `C'` and (asked) `C''`, `C'''` at roll `t`, and the root.
#[derive(Clone, Copy, Debug)]
struct Orders {
    c: [[f64; 2]; 4],
    s: f64,
}

fn orders(v: &View, outer: &[f64], t: f64, s0: f64, higher: bool, ts: &mut tape::Scratch) -> Option<Orders> {
    if v.tool == TOOL_POINT {
        let (x, _) = at(v, outer, t, true, Jet::constant(0.0), ts)?;
        return Some(Orders {
            c: std::array::from_fn(|k| {
                let f = [1.0, 1.0, 2.0, 6.0][k];
                [f * x[0].0[k], f * x[1].0[k]]
            }),
            s: 0.0,
        });
    }
    let (_, fs) = at(v, outer, t, false, Jet::var(s0), ts)?;
    let f_s = fs.0[1];
    if !(f_s != 0.0) {
        return None;
    }
    // each order of the root, one division by F_s with the order itself not yet known; an
    // analytic tool is exact at every order, so its third is too
    let top = if !higher { 1 } else if analytic(v) { 3 } else { 2 };
    let mut s = Jet::constant(s0);
    for k in 1..=top {
        let (_, f) = at(v, outer, t, true, s, ts)?;
        s.0[k] = -f.0[k] / f_s;
    }
    let (x, _) = at(v, outer, t, true, s, ts)?;
    let mut c = [[x[0].0[0], x[1].0[0]], [x[0].0[1], x[1].0[1]], [f64::NAN; 2], [f64::NAN; 2]];
    if top >= 2 {
        c[2] = [2.0 * x[0].0[2], 2.0 * x[1].0[2]];
    }
    if top >= 3 {
        c[3] = [6.0 * x[0].0[3], 6.0 * x[1].0[3]];
    }
    Some(Orders { c, s: s0 })
}

/// The memory of where each contact's root last was, keyed by where its constants live — the
/// trace's `Seen`, for a curve tool's continuation.
const SEEN_MAX: usize = 4096;

thread_local! {
    static SEEN: std::cell::RefCell<std::collections::BTreeMap<(usize, usize), (f64, f64)>> =
        std::cell::RefCell::new(std::collections::BTreeMap::new());
    static SCRATCH: std::cell::RefCell<tape::Scratch> = std::cell::RefCell::new(tape::Scratch::new());
}

/// Forget every remembered root — `System::new` calls it, as it calls `locus::forget`.
pub fn forget() {
    SEEN.with(|s| s.borrow_mut().clear());
}

/// The value and orders at roll `t`, the root carried from what this contact saw last.
fn evaluate(flat: &[f64], outer: &[f64], anchor: f64, key: Option<(usize, usize)>, higher: bool,
            ts: &mut tape::Scratch) -> Option<Orders> {
    let v = view(flat)?;
    let t = outer[0];
    let from = key.and_then(|k| SEEN.with(|s| s.borrow().get(&k).copied()));
    let s0 = carried(&v, outer, t, anchor, ts, from)?;
    let o = orders(&v, outer, t, s0, higher, ts)?;
    if let Some(k) = key {
        SEEN.with(|s| {
            let mut s = s.borrow_mut();
            if s.len() >= SEEN_MAX {
                s.clear();
            }
            s.insert(k, (t, s0));
        });
    }
    Some(o)
}

/// The evaluation a contact kernel makes: `[anchor, n_values, values…, flat…]` its constants,
/// `u` the roll and `theta` the curve's columns.  `C'` in `dx[0]`; the gradient along the
/// columns, a forward difference, in `dx[1..]` when `gradient` is asked.
pub fn kernel_eval(consts: &[f64], u: f64, theta: &[f64], higher: bool, gradient: bool) -> crate::locus::Val {
    let mut val = crate::locus::Val::default();
    let Some((anchor, values, flat)) = decode(consts) else { return val };
    let mut outer = [0.0f64; OUTER_MAX];
    let Some(outer) = outer_of(u, theta, values, &mut outer) else { return val };
    let key = (flat.as_ptr() as usize, flat.len());
    SCRATCH.with(|ts| {
        let ts = &mut *ts.borrow_mut();
        let Some(o) = evaluate(flat, outer, anchor, Some(key), higher, ts) else { return };
        val.x = o.c[0][0];
        val.y = o.c[0][1];
        val.dx[0] = o.c[1][0];
        val.dy[0] = o.c[1][1];
        if higher {
            val.d2 = o.c[2];
            val.d3 = if o.c[3].iter().all(|x| x.is_finite()) {
                o.c[3]
            } else {
                third(flat, outer, anchor, o, ts).unwrap_or([f64::NAN; 2])
            };
            val.higher = val.d2.iter().chain(&val.d3).all(|x| x.is_finite());
        }
        val.ok = true;
        if gradient {
            let Some(g) = gradients(flat, outer, anchor, o, false, ts) else {
                val.ok = false;
                return;
            };
            for j in 0..theta.len() {
                val.dx[1 + j] = g[0][0][j];
                val.dy[1 + j] = g[0][1][j];
            }
        }
    });
    val
}

/// `C'''` by a central difference of the exact `C''` — read only by a curvature's Jacobian.
fn third(flat: &[f64], outer: &[f64], anchor: f64, o: Orders, ts: &mut tape::Scratch) -> Option<[f64; 2]> {
    let v = view(flat)?;
    let h = 1e-3 * (1.0 + outer[0].abs());
    let mut probe = [0.0f64; OUTER_MAX];
    probe[..outer.len()].copy_from_slice(outer);
    let mut at_t = |t: f64, ts: &mut tape::Scratch| -> Option<[f64; 2]> {
        probe[0] = t;
        let s = carried(&v, &probe[..outer.len()], t, anchor, ts, Some((outer[0], o.s)))?;
        Some(orders(&v, &probe[..outer.len()], t, s, true, ts)?.c[2])
    };
    let (p, m) = (at_t(outer[0] + h, ts)?, at_t(outer[0] - h, ts)?);
    Some([(p[0] - m[0]) / (2.0 * h), (p[1] - m[1]) / (2.0 * h)])
}

/// Central differences of `C`, `C'` and (with `higher`) `C''` along each column, the root
/// carried from the centre's: `g[k][axis][j]`.  Central and not forward: a claim is judged by
/// the rank of a Jacobian these gradients sit in, and a forward difference's error made an
/// implied row read as independent.
fn gradients(flat: &[f64], outer: &[f64], anchor: f64, o: Orders, higher: bool, ts: &mut tape::Scratch)
    -> Option<[[[f64; tape::MAX_VARS]; 2]; 3]>
{
    let v = view(flat)?;
    let mut g = [[[0.0f64; tape::MAX_VARS]; 2]; 3];
    let mut probe = [0.0f64; OUTER_MAX];
    probe[..outer.len()].copy_from_slice(outer);
    for j in 0..v.n_theta {
        let i = 1 + j;
        let h = 1e-5 * outer[i].abs().max(1.0);
        let mut side = |x: f64, ts: &mut tape::Scratch| -> Option<Orders> {
            probe[i] = x;
            let p = &probe[..outer.len()];
            let s = if analytic(&v) { carried(&v, p, outer[0], anchor, ts, None) } else { root(&v, p, outer[0], o.s, ts) };
            let q = s.and_then(|s| orders(&v, p, outer[0], s, higher, ts));
            probe[i] = outer[i];
            q
        };
        let (up, down) = (side(outer[i] + h, ts)?, side(outer[i] - h, ts)?);
        for k in 0..if higher { 3 } else { 2 } {
            for axis in 0..2 {
                g[k][axis][j] = (up.c[k][axis] - down.c[k][axis]) / (2.0 * h);
            }
        }
    }
    Some(g)
}

/// The frame a tangency's or a curvature's Jacobian reads: the value, and the gradients of `C'`
/// and (with `higher`) `C''` along `[u, θ…]` — along `u` the next order, along the columns a
/// difference.
pub fn kernel_frame(consts: &[f64], u: f64, theta: &[f64], higher: bool) -> crate::locus::Frame {
    let val = kernel_eval(consts, u, theta, higher, true);
    let mut d1 = [[f64::NAN; tape::MAX_VARS]; 2];
    let mut d2 = [[f64::NAN; tape::MAX_VARS]; 2];
    if !val.ok {
        return crate::locus::Frame { val, d1, d2 };
    }
    let Some((anchor, values, flat)) = decode(consts) else { return crate::locus::Frame { val, d1, d2 } };
    let mut outer = [0.0f64; OUTER_MAX];
    let Some(outer) = outer_of(u, theta, values, &mut outer) else {
        return crate::locus::Frame { val, d1, d2 };
    };
    let key = (flat.as_ptr() as usize, flat.len());
    SCRATCH.with(|ts| {
        let ts = &mut *ts.borrow_mut();
        let Some(o) = evaluate(flat, outer, anchor, Some(key), higher, ts) else { return };
        let Some(g) = gradients(flat, outer, anchor, o, higher, ts) else { return };
        // along u: C'' for C', C''' for C'' — the exact order where there is one
        let (c2, c3) = if higher {
            (val.d2, val.d3)
        } else {
            let o2 = orders(&view(flat).unwrap(), outer, u, o.s, true, ts);
            (o2.map_or([f64::NAN; 2], |o| o.c[2]), [f64::NAN; 2])
        };
        for axis in 0..2 {
            d1[axis][0] = c2[axis];
            d2[axis][0] = c3[axis];
            for j in 0..theta.len() {
                d1[axis][1 + j] = g[1][axis][j];
                d2[axis][1 + j] = if higher { g[2][axis][j] } else { f64::NAN };
            }
        }
    });
    crate::locus::Frame { val, d1, d2 }
}

/// The curve over `[a, b]` as `n` chords — what the polyline draws.
pub fn sweep(flat: &[f64], outer: &[f64], anchor: f64, a: f64, b: f64, n: usize) -> Vec<(f64, f64)> {
    let Some(v) = view(flat) else { return Vec::new() };
    SCRATCH.with(|ts| {
        let ts = &mut *ts.borrow_mut();
        let mut out = Vec::with_capacity(n + 1);
        let mut probe = [0.0f64; OUTER_MAX];
        probe[..outer.len()].copy_from_slice(outer);
        let mut last: Option<(f64, f64)> = None;
        let mut point = (f64::NAN, f64::NAN);
        for k in 0..=n {
            let t = a + (b - a) * k as f64 / n.max(1) as f64;
            probe[0] = t;
            let p = &probe[..outer.len()];
            if let Some(s) = carried(&v, p, t, anchor, ts, last) {
                if let Some(o) = orders(&v, p, t, s, false, ts) {
                    point = (o.c[0][0], o.c[0][1]);
                    last = Some((t, s));
                }
            }
            out.push(point);
        }
        out
    })
}

/// Where the curve is at roll `t`, cold.
pub fn point(flat: &[f64], outer: &[f64], anchor: f64) -> (f64, f64) {
    let Some(v) = view(flat) else { return (f64::NAN, f64::NAN) };
    SCRATCH.with(|ts| {
        let ts = &mut *ts.borrow_mut();
        carried(&v, outer, outer[0], anchor, ts, None)
            .and_then(|s| orders(&v, outer, outer[0], s, false, ts))
            .map_or((f64::NAN, f64::NAN), |o| (o.c[0][0], o.c[0][1]))
    })
}

/// A contact's constants: `[anchor, n_values, values…, flat…]`.
fn decode(consts: &[f64]) -> Option<(f64, &[f64], &[f64])> {
    let &anchor = consts.first()?;
    let &nv = consts.get(1)?;
    if !(nv >= 0.0 && nv <= OUTER_MAX as f64) {
        return None;
    }
    let nv = nv as usize;
    Some((anchor, consts.get(2..2 + nv)?, consts.get(2 + nv..)?))
}

fn outer_of<'a>(u: f64, theta: &[f64], values: &[f64], into: &'a mut [f64; OUTER_MAX]) -> Option<&'a [f64]> {
    let width = 1 + theta.len() + values.len();
    if width > OUTER_MAX || 1 + theta.len() > tape::MAX_VARS {
        return None;
    }
    into[0] = u;
    into[1..1 + theta.len()].copy_from_slice(theta);
    into[1 + theta.len()..width].copy_from_slice(values);
    Some(&into[..width])
}
