// Step 4, the tip relief: a semi-topping cut beside each generating crown. A member's tip
// edges are generated by its crown's flanks near their base, the addendum from the pitch line.
// A chamfer leaves each flank `tip_relief` short of that, turned `relief_angle` so the cut
// widens toward the base, and rounds into a top inside the crown. Swept with the crown, it adds
// only the sliver between chamfer and flank: each tooth's tip edges chamfered `tip_relief` down
// its flanks. It is a cut of its own, not a kink in the crown's section, because a concave
// corner inside one sweep trims two envelopes against each other (generating-sweep row T2);
// two sweeps meet in the kernel's Boolean instead. Its round and top keep its sheet one smooth
// chart, where a sharp corner would sweep a fan through the blank.
use std
use design
use views
use pitch.gear
use pitch.trace
use crown.thickness
use crown.tooth
use crown.mate
use crown.reach
use crown.space

// Where the chamfer leaves `flank`, in a section walked counter-clockwise, its `base` on the
// right. The flank generates the member's tip edge at `mark`, the addendum from the pitch line;
// the `kink` stands `tip_relief` beyond it toward the pitch line, square to the base, and
// `level` runs through the mark along the base.
component Kink(flank: line, base: line, design: group, normal_module: Length) {
  // Seeds, rough: halfway along the flank.
  mark := point hint(x: (flank.p1.x + flank.p2.x) / 2, y: (flank.p1.y + flank.p2.y) / 2)
  along := point hint(x: mark.x + base.p2.x - base.p1.x, y: mark.y + base.p2.y - base.p1.y)
  kink := point hint(at: mark)
  level := line(mark, along)
  mark on flank
  mark distance((design.base - design.addendum) * normal_module, side: left) base
  base angle(0deg) level
  mark distance(design.tip_relief) along
  kink on flank
  kink distance(design.tip_relief, side: left) level
}

// What both chamfers share: the `top` half an addendum beyond the mark toward the pitch line,
// and as long as the round's radius.
component ChamferTop(kink: group, top: line, design: group, normal_module: Length) {
  top.p1 distance(design.addendum * normal_module / 2, side: left) kink.level
  distance(design.rounding * normal_module) top
}

// A chamfer where the walk leaves the base along `flank`: its `slope` from the base line up
// through the kink, turned the relief angle from the flank, then a round of the crown's tip
// radius into a `top` running back along the base.
component LeavingChamfer(flank: line, base: line, design: group, normal_module: Length) {
  at := Kink(flank, base, design, normal_module: normal_module)
  // Seeds, in fractions of the flank from its base end and of the base toward the section's
  // inside. They choose the branch: the round's centre stands inside the section, above the
  // kink, where a round on the far side of the slope would turn the wrong way.
  foot := point hint(x: flank.p1.x - 0.35 * (base.p1.x - base.p2.x),
                     y: flank.p1.y - 0.35 * (base.p1.y - base.p2.y))
  rc := point hint(
    x: flank.p1.x + 0.41 * (flank.p2.x - flank.p1.x) + 0.1 * (base.p1.x - base.p2.x),
    y: flank.p1.y + 0.41 * (flank.p2.y - flank.p1.y) + 0.1 * (base.p1.y - base.p2.y))
  slope_end := point hint(
    x: flank.p1.x + 0.42 * (flank.p2.x - flank.p1.x) + 0.02 * (base.p1.x - base.p2.x),
    y: flank.p1.y + 0.42 * (flank.p2.y - flank.p1.y) + 0.02 * (base.p1.y - base.p2.y))
  top_start := point hint(
    x: flank.p1.x + 0.51 * (flank.p2.x - flank.p1.x) + 0.1 * (base.p1.x - base.p2.x),
    y: flank.p1.y + 0.51 * (flank.p2.y - flank.p1.y) + 0.1 * (base.p1.y - base.p2.y))
  top_end := point hint(
    x: flank.p1.x + 0.51 * (flank.p2.x - flank.p1.x) + 0.2 * (base.p1.x - base.p2.x),
    y: flank.p1.y + 0.51 * (flank.p2.y - flank.p1.y) + 0.2 * (base.p1.y - base.p2.y))
  (slope := line(foot, slope_end)) -> tangent
    (round := arc(center: rc) hint(r: design.rounding * normal_module)) -> tangent
    (top := line(top_start, top_end))
  foot on base
  at.kink on slope
  flank angle(design.relief_angle) slope
  radius(design.rounding * normal_module) round
  base angle(180deg) top
  tops := ChamferTop(at, top, design, normal_module: normal_module)
}

// A chamfer where the walk arrives at the base along `flank`: the mirror image, walked `top`,
// round, `slope`.
component ArrivingChamfer(flank: line, base: line, design: group, normal_module: Length) {
  at := Kink(flank, base, design, normal_module: normal_module)
  // Seeds as LeavingChamfer's, from the flank's second point.
  foot := point hint(x: flank.p2.x - 0.35 * (base.p2.x - base.p1.x),
                     y: flank.p2.y - 0.35 * (base.p2.y - base.p1.y))
  rc := point hint(
    x: flank.p2.x + 0.41 * (flank.p1.x - flank.p2.x) + 0.1 * (base.p2.x - base.p1.x),
    y: flank.p2.y + 0.41 * (flank.p1.y - flank.p2.y) + 0.1 * (base.p2.y - base.p1.y))
  top_start := point hint(
    x: flank.p2.x + 0.51 * (flank.p1.x - flank.p2.x) + 0.2 * (base.p2.x - base.p1.x),
    y: flank.p2.y + 0.51 * (flank.p1.y - flank.p2.y) + 0.2 * (base.p2.y - base.p1.y))
  top_end := point hint(
    x: flank.p2.x + 0.51 * (flank.p1.x - flank.p2.x) + 0.1 * (base.p2.x - base.p1.x),
    y: flank.p2.y + 0.51 * (flank.p1.y - flank.p2.y) + 0.1 * (base.p2.y - base.p1.y))
  slope_start := point hint(
    x: flank.p2.x + 0.42 * (flank.p1.x - flank.p2.x) + 0.02 * (base.p2.x - base.p1.x),
    y: flank.p2.y + 0.42 * (flank.p1.y - flank.p2.y) + 0.02 * (base.p2.y - base.p1.y))
  (top := line(top_start, top_end)) -> tangent
    (round := arc(center: rc) hint(r: design.rounding * normal_module)) -> tangent
    (slope := line(slope_start, foot))
  foot on base
  at.kink on slope
  flank angle(design.relief_angle, sense: cw) slope
  radius(design.rounding * normal_module) round
  base angle(180deg) top
  tops := ChamferTop(at, top, design, normal_module: normal_module)
}

// The pinion's relief, beside its crown `tooth` (a CrownTooth): the material between both
// chamfers under their tops, each side closed as the gear's space is (crown/space.sv), at the
// cutter's axis beyond the outer flank and at the space cutter's `cap` beyond the inner.
component ToothRelief(tooth: group, cap: line, design: group, normal_module: Length) {
  outer_chamfer := LeavingChamfer(tooth.rack.outer, tooth.rack.base, design,
    normal_module: normal_module)
  inner_chamfer := ArrivingChamfer(tooth.rack.inner, tooth.rack.base, design,
    normal_module: normal_module)
  private outer := crown.space.FlankSection(tooth.rack.base, outer_chamfer.slope,
    outer_chamfer.round, outer_chamfer.top, tooth.axis)
  private inner := crown.space.FlankSection(tooth.rack.base, inner_chamfer.slope,
    inner_chamfer.round, inner_chamfer.top, cap)
  private construction outer_side := solid(outer.profile, about: tooth.axis)
  private construction inner_side := solid(inner.profile, about: tooth.axis)
  body := solid(outer_side)
  inner_side bound body
}

// The gear's relief, beside its space cutter (crown/space.sv): the outer mate section's inner
// chamfer within the inner one's outer chamfer indexed a crown pitch round, closed as the
// space's flanks are.
component SpaceRelief(axis: line, outside: group, inside: group, indexing: motion, cap: line,
                      design: group, normal_module: Length) {
  outer_chamfer := LeavingChamfer(outside.inner, outside.base, design,
    normal_module: normal_module)
  inner_chamfer := ArrivingChamfer(inside.outer, inside.base, design,
    normal_module: normal_module)
  private outer := crown.space.FlankSection(outside.base, outer_chamfer.slope,
    outer_chamfer.round, outer_chamfer.top, cap)
  private inner := crown.space.FlankSection(inside.base, inner_chamfer.slope,
    inner_chamfer.round, inner_chamfer.top, axis)
  private construction outer_side := solid(outer.profile, about: axis)
  private construction inner_side := solid(inner.profile, about: axis)
  private construction neighbor := solid(inner_side, under: indexing, at: 0deg)
  body := solid(outer_side)
  neighbor bound body
}

preview {
  unit mm
  pitch := views.PitchView(std.front, span: design.hypoid_design.cutter_radius)
  gear := pitch.gear.GearCone(pitch.view, g.view, design.hypoid_design)
  g := views.FoldedView(pitch.view, gear.generator, span: design.hypoid_design.cutter_radius)
  trace := pitch.trace.ToothTrace(pitch.view, gear.generator, design.hypoid_design)
  thickness := crown.thickness.CrownThickness(pitch.view, gear.generator, trace.normal,
    design.hypoid_design)
  n := views.FoldedView(pitch.view, trace.normal, span: design.hypoid_design.cutter_radius)
  tooth := crown.tooth.CrownTooth(pitch.view, trace.normal, thickness.inner_pitch,
    thickness.outer_pitch, design.hypoid_design) in n.view
  mate := crown.mate.CrownMate(tooth, design.hypoid_design) in n.view
  reach := crown.reach.CutterReach(pitch.view, n.view, gear.O, trace.normal, mate.axis,
    reach: design.hypoid_design.space_reach)
  crown_neighbor := motion(about: gear.crown_axis,
    phase: -4 * length(thickness.ahead) / radius(thickness.ahead) * 1rad)
  space := crown.space.ComplementarySpace(mate.axis, mate.outer, mate.inner, crown_neighbor,
    reach.cap) in n.view
  tooth_relief := ToothRelief(tooth, reach.cap, design.hypoid_design) in n.view
  space_relief := SpaceRelief(mate.axis, mate.outer, mate.inner, crown_neighbor, reach.cap,
    design.hypoid_design) in n.view
  // Alone, each component's normal module is its own unknown: the trace constructs it.
  trace.K distance(tooth.normal_module) trace.normal
  trace.K distance(mate.normal_module) trace.normal
  trace.K distance(tooth_relief.normal_module) trace.normal
  trace.K distance(space_relief.normal_module) trace.normal
}
