// The analytic faces of the layout (layout.sv), for the generating-system checks
// (tests/envelope/paired.rs, through pair.sv); the exported bodies do not read them. Each
// generated flank is the envelope of its crown surface under its member's generating roll,
// trimmed to the member's limits and bounded by one face loop.

// A generated surface's material: within the tip cone and the heel sphere, outside the root
// cone and the toe sphere.
component ToothRegion(source: envelope, limits: group) {
  bounded := patch(source, inside: limits.tip, inside: limits.heel,
                   outside: limits.root, outside: limits.toe)
}

// Where `wall` meets a member's toe and heel spheres.
component EndCircles(wall: surface, blank: group) {
  near := seam(wall, blank.toe.wall)
  far := seam(wall, blank.heel.wall)
}

// Where each of a member's cones meets its ends.
component BlankEnds(blank: group) {
  tip := EndCircles(blank.tip.wall, blank)
  root := EndCircles(blank.root.wall, blank)
  back := EndCircles(blank.back.wall, blank)
}

// One side of a tooth on a member's `blank`: the working `flank` and its `round`, which meets
// the envelope of the crown's tip, the member's `root`. Their seams with each other, the tip
// cone and the end spheres meet at six corners; the seven edges between them, sliced along the
// member's `axis`, close the two faces, which use their join edge in opposite directions.
component ToothSide(flank: patch, round: patch, root: patch, blank: group, ax: line) {
  join := seam(flank, round)
  root_join := seam(round, root)
  tip_edge := seam(flank, blank.tip.wall)
  toe_edge := seam(flank, blank.toe.wall)
  heel_edge := seam(flank, blank.heel.wall)
  round_toe_edge := seam(round, blank.toe.wall)
  round_heel_edge := seam(round, blank.heel.wall)

  tip_toe := vertex(tip_edge, toe_edge)
  join_toe := vertex(join, toe_edge)
  root_toe := vertex(root_join, round_toe_edge)
  tip_heel := vertex(tip_edge, heel_edge)
  join_heel := vertex(join, heel_edge)
  root_heel := vertex(root_join, round_heel_edge)

  tip_span := edge(tip_edge, from: tip_toe, to: tip_heel, along: ax)
  join_span := edge(join, from: join_toe, to: join_heel, along: ax)
  root_span := edge(root_join, from: root_toe, to: root_heel, along: ax)
  toe_span := edge(toe_edge, from: join_toe, to: tip_toe, along: ax)
  heel_span := edge(heel_edge, from: join_heel, to: tip_heel, along: ax)
  round_toe_span := edge(round_toe_edge, from: root_toe, to: join_toe, along: ax)
  round_heel_span := edge(round_heel_edge, from: root_heel, to: join_heel, along: ax)

  working := face(toe_span, tip_span, heel_span, join_span, on: flank)
  transition := face(round_toe_span, join_span, round_heel_span, root_span, on: round)
}

// `refs` is a HypoidLayout.
component ReferenceFaces(refs: group) {
  // The roll the envelopes are verified over; the gear's removal sweep (members.sv) rolls further.
  roll_span := 35deg

  pinion_ends := BlankEnds(refs.pinion_blank)
  gear_ends := BlankEnds(refs.gear_blank)

  // One envelope per edge of each crown section, copy k on the profile's k-th edge: the edge's
  // crown surface over the semicircle holding the trace (in N the trace stands at 180deg),
  // generated by the member's roll, and its material.
  repeat e in refs.tooth.rack.profile {
    pinion := surface(refs.tooth.crown, e, from: 90deg, to: 270deg)
    pinion_envelope := envelope(pinion, under: refs.generation.pinion_generation,
      from: -roll_span, to: roll_span)
    pinion_region := ToothRegion(pinion_envelope, limits: refs.pinion_design)
  }
  repeat e in refs.mate.outer.profile {
    gear_outer := surface(refs.mate.outer_crown, e, from: 90deg, to: 270deg)
    gear_outer_envelope := envelope(gear_outer, under: refs.generation.gear_generation,
      from: -roll_span, to: roll_span)
    gear_outer_region := ToothRegion(gear_outer_envelope, limits: refs.gear_design)
  }
  repeat e in refs.mate.inner.profile {
    gear_inner := surface(refs.mate.inner_crown, e, from: 90deg, to: 270deg)
    gear_inner_envelope := envelope(gear_inner, under: refs.generation.gear_generation,
      from: -roll_span, to: roll_span)
    gear_inner_region := ToothRegion(gear_inner_envelope, limits: refs.gear_design)
  }

  // Each section's edges by where they stand in its walk after the base: the tooth's run
  // outer, outer_round, tip, inner_round, inner (RackSection), its mate's the other way round
  // (MateSection). The bases and each mate section's far side go unread.
  first := 1
  first_round := 2
  tip := 3
  last_round := 4
  last := 5

  // The four sides that work: the pinion tooth's two, and the gear's two facing them.
  pinion_outer := ToothSide(pinion_region[first].bounded, pinion_region[first_round].bounded,
    pinion_region[tip].bounded, refs.pinion_blank, refs.pinion.ax)
  pinion_inner := ToothSide(pinion_region[last].bounded, pinion_region[last_round].bounded,
    pinion_region[tip].bounded, refs.pinion_blank, refs.pinion.ax)
  gear_outer_inner := ToothSide(gear_outer_region[first].bounded,
    gear_outer_region[first_round].bounded, gear_outer_region[tip].bounded, refs.gear_blank,
    refs.gear.ax)
  gear_inner_outer := ToothSide(gear_inner_region[last].bounded,
    gear_inner_region[last_round].bounded, gear_inner_region[tip].bounded, refs.gear_blank,
    refs.gear.ax)
}
